# Generated by Django 5.2.1 on 2025-08-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_rename_created_add_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='video',
        ),
        migrations.AddField(
            model_name='anime',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
