# Generated by Django 5.2.1 on 2025-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_anime_video_anime_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
