# Generated by Django 5.2.1 on 2025-08-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='video_url',
            new_name='youtube_url',
        ),
    ]
